### ISSUE TITLE
The pvproperty_with_rbv pattern doesn't work for Enum type

### ISSUE THREAD

**Issue by ronpandolfi** [caproto/caproto#477]
Seems like this pattern uses PVSpec, which doesn't accept this kwarg?
`enable = pvproperty_with_rbv(name='EnableCallbacks', value='no', enum_strings=['no', 'yes'], dtype=ChannelType.ENUM)`

...gives error:

```
Traceback (most recent call last):
  File "/home/rp/PycharmProjects/caproto/caproto/ioc_examples/areadetector_image.py", line 37, in <module>
    class DetectorGroup(PVGroup):
  File "/home/rp/PycharmProjects/caproto/caproto/ioc_examples/areadetector_image.py", line 204, in DetectorGroup
    class ImagePluginGroup(PVGroup):
  File "/home/rp/PycharmProjects/caproto/caproto/ioc_examples/areadetector_image.py", line 261, in ImagePluginGroup
    enable = pvproperty_with_rbv(name='EnableCallbacks', value='no', enum_strings=['no', 'yes'], dtype=ChannelType.ENUM)
  File "/home/rp/PycharmProjects/caproto/caproto/server/server.py", line 814, in wrapped
    prefix=name,
  File "/home/rp/PycharmProjects/caproto/caproto/server/server.py", line 684, in __init__
    self.group = group
  File "/home/rp/PycharmProjects/caproto/caproto/server/server.py", line 695, in group
    self.group_dict = group
  File "/home/rp/PycharmProjects/caproto/caproto/server/server.py", line 750, in group_dict
    self._class_dict = self._generate_class_dict()
  File "/home/rp/PycharmProjects/caproto/caproto/server/server.py", line 732, in _generate_class_dict
    for attr, pvspec in self._group_dict.items()]
  File "/home/rp/PycharmProjects/caproto/caproto/server/server.py", line 732, in <listcomp>
    for attr, pvspec in self._group_dict.items()]
  File "/home/rp/PycharmProjects/caproto/caproto/server/server.py", line 721, in _pvspec_from_info
    return PVSpec(**info)
TypeError: __new__() got an unexpected keyword argument 'enum_strings'
```

**Comment by klauer** [comment]
Does this work, by chance? `cls_kwargs=dict(enum_strings=['no', 'yes'])`.

**Comment by ronpandolfi** [comment]
It initializes, but it seems like `cls_kwargs` don't make it into the PV object. I get:

```
TimeoutError: Attempted to set EpicsSignalWithRBV(read_pv='adimage:image1:EnableCallbacks_RBV', name='det_image1_enable', parent='det_image1', value='No', timestamp=1556840524.625149, auto_monitor=False, string=True, write_pv='adimage:image1:EnableCallbacks', limits=False, put_complete=False) to value 1 and timed out after 10 seconds. Current value is 'No'.
```
