### ISSUE TITLE
worker_thread_pc example raises exception

### ISSUE THREAD

**Issue by vstadnytskyi** [caproto/caproto#530]
The example [worker_thread_pc](https://github.com/caproto/caproto/blob/master/caproto/ioc_examples/worker_thread_pc.py) raises error. I literaly copied it from the caproto examples. [Version in my repository (unchanged)](https://github.com/vstadnytskyi/caproto-sandbox/blob/master/caproto_sandbox/worker_thread_pc.py)
```python
>>> caproto.__version__
'0.4.0'
```

``` shell
$ python3 caproto_sandbox/worker_thread_pc.py 
[I 16:22:34.648          server:  161] Asyncio server starting up...
[I 16:22:34.648          server:  174] Listening on 0.0.0.0:5064
[I 16:22:34.649          server:  260] Server startup complete.
* request method called at server startup
[E 16:22:34.649          server:  278] Server error. Will shut down
    Traceback (most recent call last):
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/caproto/asyncio/server.py", line 265, in run
        await asyncio.gather(*tasks)
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/caproto/server/server.py", line 137, in _server_startup
        return await self.startup(self, async_lib)
      File "caproto_sandbox/worker_thread_pc.py", line 29, in request
        self.Event = async_lib.Event
    AttributeError: 'AsyncioAsyncLayer' object has no attribute 'Event'
[I 16:22:34.650          server:  281] Server exiting....
Traceback (most recent call last):
  File "caproto_sandbox/worker_thread_pc.py", line 53, in <module>
    run(ioc.pvdb, **run_options)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/caproto/server/__init__.py", line 11, in run
    return run(pvdb, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/caproto/asyncio/server.py", line 312, in run
    loop.run_until_complete(task)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 579, in run_until_complete
    return future.result()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/caproto/asyncio/server.py", line 300, in start_server
    ret = await ctx.run(log_pv_names=log_pv_names)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/caproto/asyncio/server.py", line 265, in run
    await asyncio.gather(*tasks)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/caproto/server/server.py", line 137, in _server_startup
    return await self.startup(self, async_lib)
  File "caproto_sandbox/worker_thread_pc.py", line 29, in request
    self.Event = async_lib.Event
AttributeError: 'AsyncioAsyncLayer' object has no attribute 'Event'
```

``` python
> pm()                                                                                                                              
caproto_sandbox/worker_thread_pc.py(29)request()
-> self.Event = async_lib.Event
(Pdb) async_lib
<caproto.asyncio.server.AsyncioAsyncLayer object at 0x10f1f4b10>
```

I can import caproto and create caproto.asyncio.server.AsyncioAsyncLayer
``` python
In [4]: import caproto                                                                                                                    
In [5]: p = caproto.asyncio.server.AsyncioAsyncLayer                                                                                      
In [6]: p.__dict__                                                                                                                        
Out[6]: 
mappingproxy({'__module__': 'caproto.asyncio.server',
              'name': 'asyncio',
              'ThreadsafeQueue': None,
              'library': <module 'asyncio' from '/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/__init__.py'>,
              '__init__': <function caproto.asyncio.server.AsyncioAsyncLayer.__init__(self, loop=None)>,
              '__doc__': None})
```

Made a copy of this issue in https://github.com/vstadnytskyi/caproto-sandbox/issues/4 so I can keep adding information to it without spamming here.

**Comment by danielballan** [comment]
You need v0.4.1. You might have missed [this comment](https://github.com/caproto/caproto/issues/521#issuecomment-538775977).

**Comment by danielballan** [comment]
Did updating to v0.4.1 fix the issue?

**Comment by vstadnytskyi** [comment]
Yes, it has fixed the problem.
