### ISSUE TITLE
caproto-put fails to assign enum type PVs

### ISSUE THREAD

**Issue by MikeHart85** [caproto/caproto#564]
Cannot find a way to successfully assign enum PVs using `caproto-put`.

`caproto-get` works as expected.

Easy way to reproduce if `docker` available:

```bash
# Terminal 1
$ docker run -it dmscid/lewis chopper
(Ctrl-C to quit)

# Terminal 2
$ caproto-get AutoPark
AutoPark                                  [false]
$ caproto-get -d int AutoPark
AutoPark                                  [0]
$ caproto-put AutoPark 1
'int' object is not subscriptable
$ caproto-put AutoPark true
invalid literal for int() with base 10: 'true'
$ caproto-get AutoPark
AutoPark                                  [false]
```

To verify PV type and possible values:
```bash
$ caget -d 31 AutoPark
AutoPark
    Native data type: DBF_ENUM
    Request type:     DBR_CTRL_ENUM
    Element count:    1
    Value:            false
    Status:           NO_ALARM
    Severity:         NO_ALARM
    Enums:            ( 2)
                      [ 0] false
                      [ 1] true
```
Using `caget` here because `caproto-get` seems to ignore option `-d 31` / request type `DBR_CTRL_ENUM`.

**Comment by MikeHart85** [comment]
Verbose outputs:

```bash
$ caproto-put -vvv AutoPark 1
[D 11:35:39.751             put:  121] [AutoPark] Data argument 1 parsed as 1 (Python type int).
[D 11:35:39.751        repeater:  221] Another repeater is already running; will not spawn one.
[D 11:35:39.751          client:   54] Registering with the Channel Access repeater.
[D 11:35:39.752          client:   64] Searching for 'AutoPark'....
[D 11:35:39.752          client:   81] Search request sent to ('127.0.0.1', 5064).
[D 11:35:39.752          client:   81] Search request sent to ('172.17.255.255', 5064).
[D 11:35:39.752          client:   81] Search request sent to ('130.199.219.255', 5064).
[D 11:35:39.753          client:  121] Found AutoPark at ('172.17.0.2', 5064)
[D 11:35:39.754        _circuit:  161] [172.17.0.1:58644] --->>> [172.17.0.2:5064] (16B) VersionRequest(priority=0, version=13)
[D 11:35:39.762        _circuit:  161] [172.17.0.1:58644] --->>> [172.17.0.2:5064] (32B) HostNameRequest(name='LPS-163571')
[D 11:35:39.763        _circuit:  161] [172.17.0.1:58644] --->>> [172.17.0.2:5064] (24B) ClientNameRequest(name='mhart')
[D 11:35:39.763        _circuit:  161] [172.17.0.1:58644] --->>> [172.17.0.2:5064] [AutoPark] (32B) CreateChanRequest(name='AutoPark', cid=0, version=13)
[D 11:35:39.764        _circuit:  202] [172.17.0.1:58644] <<<--- [172.17.0.2:5064] (16B) VersionResponse(version=12)
[D 11:35:39.764        _circuit:  202] [172.17.0.1:58644] <<<--- [172.17.0.2:5064] (16B) AccessRightsResponse(cid=0, access_rights=<AccessRights.WRITE|READ: 3>)
[D 11:35:39.765        _circuit:  202] [172.17.0.1:58644] <<<--- [172.17.0.2:5064] (16B) CreateChanResponse(data_type=<ChannelType.ENUM: 3>, data_count=1, cid=0, sid=1)
[I 11:35:39.765          client:  169] [AutoPark] AutoPark connected
[D 11:35:39.765          client:  185] [AutoPark] Detected native data_type <ChannelType.ENUM: 3>.
[D 11:35:39.766          client:  189] [AutoPark] Changing requested data_type to STRING.
[D 11:35:39.766        _circuit:  161] [172.17.0.1:58644] --->>> [172.17.0.2:5064] (16B) ReadNotifyRequest(data_type=<ChannelType.STRING: 0>, data_count=1, sid=1, ioid=0)
[D 11:35:39.767        _circuit:  202] [172.17.0.1:58644] <<<--- [172.17.0.2:5064] (24B) ReadNotifyResponse(data=[b'false'], data_type=<ChannelType.STRING: 0>, data_count=1, status=CAStatusCode(name='ECA_NORMAL', code=0, code_with_severity=1, severity=<CASeverity.SUCCESS: 1>, success=1, defunct=False, description='Normal successful completion'), ioid=0, metadata=None)
[D 11:35:39.767          client:  466] Detected native data_type <ChannelType.ENUM: 3>.
[D 11:35:39.768        _circuit:  161] [172.17.0.1:58644] --->>> [172.17.0.2:5064] (16B) ClearChannelRequest(sid=1, cid=0)
Traceback (most recent call last):
  File "/home/mhart/miniconda3/envs/bluesky_py36/bin/caproto-put", line 10, in <module>
    sys.exit(main())
  File "/home/mhart/miniconda3/envs/bluesky_py36/lib/python3.6/site-packages/caproto/commandline/put.py", line 129, in main
    repeater=not args.no_repeater)
  File "/home/mhart/miniconda3/envs/bluesky_py36/lib/python3.6/site-packages/caproto/sync/client.py", line 643, in read_write_read
    res = _write(chan, data, metadata, timeout, write_data_type, notify)
  File "/home/mhart/miniconda3/envs/bluesky_py36/lib/python3.6/site-packages/caproto/sync/client.py", line 472, in _write
    if (ntype is ChannelType.ENUM) and isinstance(data[0], bytes):
TypeError: 'int' object is not subscriptable
```

---------

```bash
$ caproto-put -vvv AutoPark true
[D 12:35:08.332             put:  121] [AutoPark] Data argument true parsed as 'true' (Python type str).
[D 12:35:08.332        repeater:  221] Another repeater is already running; will not spawn one.
[D 12:35:08.332          client:   54] Registering with the Channel Access repeater.
[D 12:35:08.333          client:   64] Searching for 'AutoPark'....
[D 12:35:08.333          client:   81] Search request sent to ('127.0.0.1', 5064).
[D 12:35:08.334          client:   81] Search request sent to ('172.17.255.255', 5064).
[D 12:35:08.334          client:   81] Search request sent to ('130.199.219.255', 5064).
[D 12:35:08.334          client:  121] Found AutoPark at ('172.17.0.2', 5064)
[D 12:35:08.335        _circuit:  161] [172.17.0.1:59848] --->>> [172.17.0.2:5064] (16B) VersionRequest(priority=0, version=13)
[D 12:35:08.336        _circuit:  161] [172.17.0.1:59848] --->>> [172.17.0.2:5064] (32B) HostNameRequest(name='LPS-163571')
[D 12:35:08.336        _circuit:  161] [172.17.0.1:59848] --->>> [172.17.0.2:5064] (24B) ClientNameRequest(name='mhart')
[D 12:35:08.336        _circuit:  161] [172.17.0.1:59848] --->>> [172.17.0.2:5064] [AutoPark] (32B) CreateChanRequest(name='AutoPark', cid=0, version=13)
[D 12:35:08.336        _circuit:  202] [172.17.0.1:59848] <<<--- [172.17.0.2:5064] (16B) VersionResponse(version=12)
[D 12:35:08.336        _circuit:  202] [172.17.0.1:59848] <<<--- [172.17.0.2:5064] (16B) AccessRightsResponse(cid=0, access_rights=<AccessRights.WRITE|READ: 3>)
[D 12:35:08.336        _circuit:  202] [172.17.0.1:59848] <<<--- [172.17.0.2:5064] (16B) CreateChanResponse(data_type=<ChannelType.ENUM: 3>, data_count=1, cid=0, sid=1)
[I 12:35:08.337          client:  169] [AutoPark] AutoPark connected
[D 12:35:08.337          client:  185] [AutoPark] Detected native data_type <ChannelType.ENUM: 3>.
[D 12:35:08.337          client:  189] [AutoPark] Changing requested data_type to STRING.
[D 12:35:08.337        _circuit:  161] [172.17.0.1:59848] --->>> [172.17.0.2:5064] (16B) ReadNotifyRequest(data_type=<ChannelType.STRING: 0>, data_count=1, sid=1, ioid=0)
[D 12:35:08.337        _circuit:  202] [172.17.0.1:59848] <<<--- [172.17.0.2:5064] (24B) ReadNotifyResponse(data=[b'false'], data_type=<ChannelType.STRING: 0>, data_count=1, status=CAStatusCode(name='ECA_NORMAL', code=0, code_with_severity=1, severity=<CASeverity.SUCCESS: 1>, success=1, defunct=False, description='Normal successful completion'), ioid=0, metadata=None)
[D 12:35:08.338          client:  466] Detected native data_type <ChannelType.ENUM: 3>.
[D 12:35:08.338          client:  475] Writing.
[D 12:35:08.338        _circuit:  161] [172.17.0.1:59848] --->>> [172.17.0.2:5064] (16B) ClearChannelRequest(sid=1, cid=0)
Traceback (most recent call last):
  File "/home/mhart/miniconda3/envs/bluesky_py36/bin/caproto-put", line 10, in <module>
    sys.exit(main())
  File "/home/mhart/miniconda3/envs/bluesky_py36/lib/python3.6/site-packages/caproto/commandline/put.py", line 129, in main
    repeater=not args.no_repeater)
  File "/home/mhart/miniconda3/envs/bluesky_py36/lib/python3.6/site-packages/caproto/sync/client.py", line 643, in read_write_read
    res = _write(chan, data, metadata, timeout, write_data_type, notify)
  File "/home/mhart/miniconda3/envs/bluesky_py36/lib/python3.6/site-packages/caproto/sync/client.py", line 477, in _write
    data_type=data_type, metadata=metadata)
  File "/home/mhart/miniconda3/envs/bluesky_py36/lib/python3.6/site-packages/caproto/_circuit.py", line 725, in write
    metadata=metadata)
  File "/home/mhart/miniconda3/envs/bluesky_py36/lib/python3.6/site-packages/caproto/_commands.py", line 1161, in __init__
    size, *buffers = data_payload(data, metadata, data_type, data_count)
  File "/home/mhart/miniconda3/envs/bluesky_py36/lib/python3.6/site-packages/caproto/_commands.py", line 258, in data_payload
    native_type(data_type), data, byteswap=True)
  File "/home/mhart/miniconda3/envs/bluesky_py36/lib/python3.6/site-packages/caproto/_numpy_backend.py", line 64, in python_to_epics
    return np.asarray(values).astype(type_map[dtype])
ValueError: invalid literal for int() with base 10: 'true'
```

**Comment by danielballan** [comment]
:+1: :+1: :+1: for Lewis Docker containers making it much easier to run minimal examples with epics-base IOCs!

**Comment by MikeHart85** [comment]
If we make a caproto adapter for it, you could even just pip install it and run without docker.

You can now as well, of course, but you'd need EPICS base installed to run the EPICS devices.

**Comment by MikeHart85** [comment]
This issue looks like a one-line fix in `sync/client.py`'s `def _write`... the "is this a string" condition is both throwing an exception when `data` is of type `int`, and failing to recognize `data` of type `str` as a string.

I'll make a PR in after lunch.
