### ISSUE TITLE
Fix ophyd AD example

### ISSUE THREAD

**Issue by danielballan** [caproto/caproto#572]
Our Travis-CI cron is failing because ophyd is pickier about array shape now

https://travis-ci.org/github/caproto/caproto/jobs/664884716

```
--------------------------------------
Running caproto.ioc_examples.areadetector_image with coverage
/home/travis/build/caproto/caproto
Arguments: ['/home/travis/build/caproto/caproto/caproto/tests/example_runner.py', '--prefix', '785f08b0:', '--async-lib', 'curio', '-vvv']
Connected to detector
----------------------------- Captured stderr call -----------------------------
Traceback (most recent call last):
  File "/opt/python/3.6.7/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/python/3.6.7/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/travis/build/caproto/caproto/caproto/tests/example_runner.py", line 45, in <module>
    runpy.run_module(example_module, run_name='__main__')
  File "/opt/python/3.6.7/lib/python3.6/runpy.py", line 208, in run_module
    return _run_code(code, {}, init_globals, run_name, mod_spec)
  File "/opt/python/3.6.7/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/travis/build/caproto/caproto/caproto/ioc_examples/areadetector_image.py", line 335, in <module>
    generate_detector_code()
  File "/home/travis/build/caproto/caproto/caproto/ioc_examples/areadetector_image.py", line 318, in generate_detector_code
    dev_dict = ophyd_device_to_caproto_ioc(my_detector)
  File "/home/travis/build/caproto/caproto/caproto/server/conversion.py", line 158, in ophyd_device_to_caproto_ioc
    dev=dev)
  File "/home/travis/build/caproto/caproto/caproto/server/conversion.py", line 48, in ophyd_component_to_caproto
    cpt_dict = ophyd_device_to_caproto_ioc(to_describe, depth=depth)
  File "/home/travis/build/caproto/caproto/caproto/server/conversion.py", line 158, in ophyd_device_to_caproto_ioc
    dev=dev)
  File "/home/travis/build/caproto/caproto/caproto/server/conversion.py", line 67, in ophyd_component_to_caproto
    value = sig.get()
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/ophyd/signal.py", line 590, in get
    self._readback = self.inverse(value)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/ophyd/areadetector/base.py", line 107, in inverse
    raise RuntimeError(f"Invalid array size {self.derived_shape}")
RuntimeError: Invalid array size (0, 0, 0)
__________________________ test_areadetector_generate __________________________
    @pytest.mark.skipif(sys.platform == 'win32',
                        reason='win32 AD IOC')
    def test_areadetector_generate():
        pytest.importorskip('numpy')
        from caproto.ioc_examples import areadetector_image
    
        # smoke-test the generation code
>       areadetector_image.generate_detector_code()
caproto/tests/test_examples.py:421: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
caproto/ioc_examples/areadetector_image.py:318: in generate_detector_code
    dev_dict = ophyd_device_to_caproto_ioc(my_detector)
caproto/server/conversion.py:158: in ophyd_device_to_caproto_ioc
    dev=dev)
caproto/server/conversion.py:48: in ophyd_component_to_caproto
    cpt_dict = ophyd_device_to_caproto_ioc(to_describe, depth=depth)
caproto/server/conversion.py:158: in ophyd_device_to_caproto_ioc
    dev=dev)
caproto/server/conversion.py:67: in ophyd_component_to_caproto
    value = sig.get()
../../../virtualenv/python3.6.7/lib/python3.6/site-packages/ophyd/signal.py:590: in get
    self._readback = self.inverse(value)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
self = NDDerivedSignal(name='detector_image1_shaped_image', parent='detector_image1', value=0.0, timestamp=631152000.0, derived_from='image1.array_data')
value = array([], dtype=uint8)
    def inverse(self, value):
        """Shape the flat array to send as a result of ``.get``"""
        array_shape = self.derived_shape[:self.derived_ndims]
        if not any(array_shape):
>           raise RuntimeError(f"Invalid array size {self.derived_shape}")
E           RuntimeError: Invalid array size (0, 0, 0)
../../../virtualenv/python3.6.7/lib/python3.6/site-packages/ophyd/areadetector/base.py:107: RuntimeError
----------------------------- Captured stdout call -----------------------------
Connected to detector
```

**Comment by klauer** [comment]
I'd say either xfail or remove it for now... It's been problematic from the get-go on CI.

**Comment by tacaswell** [comment]
:+1: to xfail

**Comment by klauer** [comment]
Also failing:
```
test_areadetector_generate
```

**Comment by klauer** [comment]
This is in the category of #616
