### ISSUE TITLE
Identify areas where unbounded dictionaries/lists/etc could be a problem

### ISSUE THREAD

**Issue by klauer** [caproto/caproto#647]
Ran into a scenario where an IOC host consumed all of its memory. 

While it's unclear if caproto was the root cause of that memory consumption, it happened to be the machine running our first ever production caproto IOC (v0.6.0). It was interacting with likely hundreds of other CA clients indirectly through UDP.

```
[E 11:32:36.768       common:  768] Broadcaster command queue evaluation failed
    Traceback (most recent call last):
      File "(caproto-env)/caproto-dev/caproto/server/common.py", line 763, in broadcaster_queue_loop
        await self._broadcaster_queue_iteration(addr, commands)
      File "(caproto-env)/caproto-dev/caproto/server/common.py", line 819, in _broadcaster_queue_iteration
        self.broadcaster.process_commands(commands)
      File "(caproto-env)/caproto-dev/caproto/_broadcaster.py", line 155, in process_commands
        self._process_command(self.their_role, command, history)
      File "(caproto-env)/caproto-dev/caproto/_broadcaster.py", line 177, in _process_command
        self.unanswered_searches[command.cid] = command.name
    MemoryError
```

Unanswered searches here is technically unbounded, but its domain is limited to `(0...2**16 - 1)`, so it couldn't be the actual issue.

Regardless, there's a need here to do a deep dive and identify areas where unbounded items could bring down servers or even long-running clients.

**Comment by tacaswell** [comment]
This is the broadcaster seeing searches from clients to hosts IOCs it is not sitting in front of so they never get cleared?
