### ISSUE TITLE
 ERROR: Task exception was never retrieved.  KeyError: 5635

### ISSUE THREAD

**Issue by vstadnytskyi** [caproto/caproto#711]
Hello All,

I have examined logs of my data acquisition unit and found that caproto had this error. It didn't break the operation of the code but is it something one should worry about? The error key in the example below does not description so I don't know if It is something I should worry about. Do you have a list of KeyErrors?

```
2021-01-27 08:35:02,109 ERROR: Task exception was never retrieved
future: <Task finished name='Task-150325' coro=<Context.tcp_handler() done, defined at /home/femtoland/.local/lib/python3.8/site-packages/caproto/server/common.py:1073> exception=KeyError(5635)>
Traceback (most recent call last):
  File "/home/femtoland/.local/lib/python3.8/site-packages/caproto/server/common.py", line 1086, in tcp_handler
    await circuit.recv()
  File "/home/femtoland/.local/lib/python3.8/site-packages/caproto/server/common.py", line 163, in recv
    commands, _ = self.circuit.recv(bytes_received)
  File "/home/femtoland/.local/lib/python3.8/site-packages/caproto/_circuit.py", line 198, in recv
    num_bytes_needed) = read_from_bytestream(self._data,
  File "/home/femtoland/.local/lib/python3.8/site-packages/caproto/_commands.py", line 368, in read_from_bytestream
    _class = Commands[role][header.command]
KeyError: 5635
```

This is done by my IT department that constantly scans ports for vulnerabilities. I don't know if I should tell them to stop or it is OK and they don't really break anything in caprot. See logs below.

```
2021-01-27 08:34:42,070 INFO: Connected to new client at xxx.187.82.151:40872 (total: 2).
2021-01-27 08:34:52,004 INFO: Disconnected from client at xxx.187.82.151:40872 (total: 1).
2021-01-27 08:34:52,020 INFO: Connected to new client at xxx.187.82.151:41504 (total: 2).
2021-01-27 08:34:52,021 INFO: Connected to new client at xxx.187.82.151:41506 (total: 3).
2021-01-27 08:34:52,101 INFO: Connected to new client at xxx.187.82.151:41522 (total: 4).
2021-01-27 08:34:52,364 INFO: Connected to new client at xxx.187.82.151:41552 (total: 5).
2021-01-27 08:34:56,003 INFO: Disconnected from client at xxx.187.82.151:41522 (total: 4).
2021-01-27 08:34:57,025 INFO: Disconnected from client at xxx.187.82.151:41504 (total: 3).
2021-01-27 08:34:57,025 INFO: Disconnected from client at xxx.187.82.151:41506 (total: 2).
2021-01-27 08:34:57,063 INFO: Connected to new client at xxx.187.82.151:41972 (total: 3).
2021-01-27 08:34:57,108 INFO: Connected to new client at xxx.187.82.151:41994 (total: 4).
2021-01-27 08:34:57,367 INFO: Disconnected from client at xxx.187.82.151:41552 (total: 3).
2021-01-27 08:34:57,464 INFO: Connected to new client at xxx.187.82.151:42066 (total: 4).
2021-01-27 08:35:00,220 INFO: Connected to new client at xxx.187.82.151:42256 (total: 5).
2021-01-27 08:35:02,068 INFO: Disconnected from client at xxx.187.82.151:41972 (total: 4).
2021-01-27 08:35:02,069 INFO: Connected to new client at xxx.187.82.151:42288 (total: 5).
2021-01-27 08:35:02,108 INFO: Disconnected from client at xxx.187.82.151:41994 (total: 4).
2021-01-27 08:35:02,109 INFO: Connected to new client at xxx.187.82.151:42292 (total: 5).
2021-01-27 08:35:02,109 ERROR: Task exception was never retrieved
future: <Task finished name='Task-150325' coro=<Context.tcp_handler() done, defined at /home/femtoland/.local/lib/python3.8/site-packages/caproto/server/common.py:1073> exception=KeyError(5635)>
Traceback (most recent call last):
  File "/home/femtoland/.local/lib/python3.8/site-packages/caproto/server/common.py", line 1086, in tcp_handler
    await circuit.recv()
  File "/home/femtoland/.local/lib/python3.8/site-packages/caproto/server/common.py", line 163, in recv
    commands, _ = self.circuit.recv(bytes_received)
  File "/home/femtoland/.local/lib/python3.8/site-packages/caproto/_circuit.py", line 198, in recv
    num_bytes_needed) = read_from_bytestream(self._data,
  File "/home/femtoland/.local/lib/python3.8/site-packages/caproto/_commands.py", line 368, in read_from_bytestream
    _class = Commands[role][header.command]
KeyError: 5635
2021-01-27 08:35:05,225 INFO: Disconnected from client at xxx.187.82.151:42256 (total: 4).
2021-01-27 08:35:08,070 INFO: Disconnected from client at xxx.187.82.151:42288 (total: 3).
2021-01-27 08:35:57,464 INFO: Disconnected from client at xxx.187.82.151:42066 (total: 2).
2021-01-27 08:36:07,281 INFO: Connected to new client at xxx.187.82.151:54150 (total: 3).
2021-01-27 08:36:07,284 INFO: Disconnected from client at xxx.187.82.151:54150 (total: 2).
```

**Comment by klauer** [comment]
Is the client also a caproto-based or something else? If so (and perhaps even if not), this issue is definitely concerning.
Can you reliably reproduce this?

Background details:
Valid message IDs are `0 <= id <= 27`, where for example `ID = 22` in `AccessRightsResponse` (https://github.com/caproto/caproto/blob/16b06d1ffd97f8c850db315c1215cfdb829f85f4/caproto/_commands.py#L1680-L1698) allows for caproto to see 22 in a packet, instantiate the above class, and provide a more user-friendly interface to the information contained.

Rather than an indicator of a new and unhandled message type, this is likely a packet which was misaligned/incorrectly-generated/cut off when being sent/etc.

**Comment by vstadnytskyi** [comment]
@klauer 

This happens every morning at around 8:30 am. The IP address of the client corresponds to the IT security scanning server that scans ports for vulnerabilities. It is not a CA client. I don't know what they are actually doing.

From my log above you can see that my institute IT "client" connect/disconnects multiple time during the scan.

**Comment by klauer** [comment]
Ah-ha, reading comprehension is not my strong suit, obviously!

The security scan shouldn't break the caproto server; it will just spam annoying messages like that. 
I think there's nothing really to worry about here.

**Comment by klauer** [comment]
Thinking a bit more about it, I'd like caproto to output a better message in this scenario. `softIoc` dumps out something like this:
```
CAS: Request from x.y.z.148:42174 => cmmd=769 cid=0x3b0000 type=7 count=0 postsize=2560
CAS: Request from x.y.z.148:42174 =>   available=0x0       N=0 paddr=(nil)
```
But even this is a bit cryptic and out-of-order with respect to how the header packet is serialized strangely.
