### ISSUE TITLE
Failure to run simple ioc example on Windows under Python 3.8

### ISSUE THREAD

**Issue by mfurseman** [caproto/caproto#733]
When attempting to run the simple IOC example on Windows 10 (Version 20H2 19042.804) and Python 3.8 I always get the following error. caproto is installed from master (6021863). It seems there is some incompatibility with the Python Windows API:
```
C:\Users\XXX\AppData\Roaming\Python\Python38\site-packages\caproto\ioc_examples>"c:\Program Files\Python38\python.exe" simple.py
[I 15:30:01.438       server:  133] Asyncio server starting up...
[I 15:30:01.438       server:  146] Listening on 0.0.0.0:5064
[E 15:30:01.439        utils:   59] <caproto.asyncio.utils._DatagramProtocol object at 0x00000244492A8640> receive error
    Traceback (most recent call last):
      File "c:\Program Files\Python38\lib\asyncio\proactor_events.py", line 563, in _loop_reading
        self._read_fut = self._loop._proactor.recv(self._sock,
      File "c:\Program Files\Python38\lib\asyncio\windows_events.py", line 445, in recv
        ov.WSARecv(conn.fileno(), nbytes, flags)
    OSError: [WinError 10022] An invalid argument was supplied
[I 15:30:01.441       server:  205] Server startup complete.
```
I'd be extremely grateful if someone could help me out!

**Comment by klauer** [comment]
Thanks for the report, @mfurseman. #720 should resolve this once it's merged, but so far it's not quite finished yet.

The error message is specifically coming from the beacon message broadcasting. If you're in need of an immediate fix, you can comment out this block:

```patch
diff --git a/caproto/asyncio/server.py b/caproto/asyncio/server.py
index 69a3ffe1..6318cb93 100644
--- a/caproto/asyncio/server.py
+++ b/caproto/asyncio/server.py
@@ -165,15 +165,15 @@ class Context(_Context):
                 return self.transport.close()
 
         reuse_port = sys.platform not in ('win32', ) and hasattr(socket, 'SO_REUSEPORT')
-        for address in ca.get_beacon_address_list():
-            transport, _ = await self.loop.create_datagram_endpoint(
-                functools.partial(_DatagramProtocol, parent=self,
-                                  recv_func=self._datagram_received),
-                remote_addr=address, allow_broadcast=True,
-                reuse_port=reuse_port)
-            wrapped_transport = ConnectedTransportWrapper(transport, address)
-            self.beacon_socks[address] = (interface,   # TODO; this is incorrect
-                                          wrapped_transport)
+        # for address in ca.get_beacon_address_list():
+        #     transport, _ = await self.loop.create_datagram_endpoint(
+        #         functools.partial(_DatagramProtocol, parent=self,
+        #                           recv_func=self._datagram_received),
+        #         remote_addr=address, allow_broadcast=True,
+        #         reuse_port=reuse_port)
+        #     wrapped_transport = ConnectedTransportWrapper(transport, address)
+        #     self.beacon_socks[address] = (interface,   # TODO; this is incorrect
+        #                                   wrapped_transport)
 
         for interface in self.interfaces:
             sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM, socket.IPPROTO_UDP)
```

Some clients may complain about the lack of beacon notifications, but I think it should work "enough" for you to play around with caproto.

**Comment by mfurseman** [comment]
Thank you, this works for us!
