### ISSUE TITLE
Windows: An attempt was made to access a socket in a way forbidden by its access permissions

### ISSUE THREAD

**Issue by klauer** [caproto/caproto#756]
Random failure on Windows CI - out of several thousand tests:
```
2021-03-16T18:48:20.0641843Z   File "D:\a\caproto\caproto\caproto\curio\server.py", line 135, in broadcaster_udp_server_loop
2021-03-16T18:48:20.0642992Z     udp_sock.bind((interface, self.ca_server_port))
2021-03-16T18:48:20.0643978Z OSError: [WinError 10013] An attempt was made to access a socket in a way forbidden by its access permissions
2021-03-16T18:48:20.0645321Z ERROR    curio.kernel:kernel.py:755 Task Crash: Task(id=197, name='Context.broadcaster_udp_server_loop', state='TERMINATED')
2021-03-16T18:48:20.0646251Z Traceback (most recent call last):
2021-03-16T18:48:20.0647355Z   File "c:\hostedtoolcache\windows\python\3.7.9\x64\lib\site-packages\curio\kernel.py", line 736, in kernel_run
2021-03-16T18:48:20.0649089Z     trap = current.send(current._trap_result)
2021-03-16T18:48:20.0650026Z   File "c:\hostedtoolcache\windows\python\3.7.9\x64\lib\site-packages\curio\task.py", line 167, in send
2021-03-16T18:48:20.0650831Z     return self._send(value)
2021-03-16T18:48:20.0651720Z   File "c:\hostedtoolcache\windows\python\3.7.9\x64\lib\site-packages\curio\task.py", line 171, in _task_runner
2021-03-16T18:48:20.0652508Z     return await coro
2021-03-16T18:48:20.0653524Z   File "D:\a\caproto\caproto\caproto\curio\server.py", line 135, in broadcaster_udp_server_loop
2021-03-16T18:48:20.0654950Z     udp_sock.bind((interface, self.ca_server_port))
2021-03-16T18:48:20.0655885Z OSError: [WinError 10013] An attempt was made to access a socket in a way forbidden by its access permissions```

_Originally posted by @klauer in https://github.com/caproto/caproto/issues/754#issuecomment-800533646_

**Comment by klauer** [comment]
I redid windows support for servers (https://github.com/caproto/caproto/pull/794 and at least one other PR) and have found it to be rather stable so far. Closing for now.
