### ISSUE TITLE
caproto without wifi\ethernet

### ISSUE THREAD

**Issue by vstadnytskyi** [caproto/caproto#782]
I have noticed that caproto server does not work if there is no active TCP/IP (ethernet or wifi) connection. It seems to be a prerequisite. Here is a problem I am facing. I have an instrument that has 2 caproto servers and a PyEPICS GUI. They all are part of one system. Today, the ethernet switches went down because of power outage and a laptop lost ethernet connection. The backup power on the laptop and the instrument would have continued working but the software stopped because there were no ethernet connection. My understand is that caproto or any other python sockets use IP loopback for communication within localhost. IS there a way to keep it working even if laptop has no connection to ethernet nor WIFI.

I get this error if I turn off wifi on my laptop.
```
[E 17:14:17.147        utils:   59] <caproto.asyncio.utils._DatagramProtocol object at 0x7fa0698cdb90> receive error
    Traceback (most recent call last):
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/selector_events.py", line 992, in sendto
        self._sock.sendto(data, addr)
    OSError: [Errno 51] Network is unreachable
ERROR:caproto.ctx:<caproto.asyncio.utils._DatagramProtocol object at 0x7fa0698cdb90> receive error
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/selector_events.py", line 992, in sendto
    self._sock.sendto(data, addr)
OSError: [Errno 51] Network is unreachable
```

**Comment by friedrich-schotte** [comment]
If client and server are always running on the same machine, I recommend adding the following lines to your your ~/.bashrc:
 
export EPICS_CA_AUTO_ADDR_LIST=no
export EPICS_CA_ADDR_LIST=127.0.0.1

That would make the client to server communication impervious to any network disruptions.
