### ISSUE TITLE
Server traceback when reading a float

### ISSUE THREAD

**Issue by kc64** [caproto/caproto#840]
I have a PV defined as follows:

`flow_rate = pvproperty(name='FLOW_RATE', value=0.0, max_length=1, units='gpm', dtype=Double, doc='The chiller internal sensed flow rate.') #, read_only=True)`

When I attempt to access it, I get the following server traceback:

`Server failed to process command ('A:CHILLER1:FLOW_RATE'): ReadNotifyRequest(data_type=<ChannelType.DOUBLE: 6>, data_count=0, sid=0, ioid=0)
Traceback (most recent call last):
  File "/home/app/.venv-3.10/lib/python3.10/site-packages/caproto/server/common.py", line 284, in _command_queue_iteration
    response = await self._process_command(command)
  File "/home/app/.venv-3.10/lib/python3.10/site-packages/caproto/server/common.py", line 598, in _process_command
    data_count = db_entry.calculate_length(data)
  File "/home/app/.venv-3.10/lib/python3.10/site-packages/caproto/_data.py", line 346, in calculate_length
    return len(value)
TypeError: len() of unsized object
`

I've been poring over the caproto code base for hours and still have not tracked down what I'm doing wrong. Can anyone help?

**Comment by kc64** [comment]
We just discovered issue. The data was being pushed into the pvdb as '2.3' (a string) instead of 2.3 (a float). Embarrassing but a relief. Thanks for trying to help.
